"""add role

Revision ID: 31eb1659d473
Revises: ebe3698fff65
Create Date: 2024-02-15 10:08:27.598279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31eb1659d473'
down_revision: Union[str, None] = 'ebe3698fff65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Role_id'), 'Role', ['id'], unique=False)
    op.add_column('Account', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Account', 'Role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Account', type_='foreignkey')
    op.drop_column('Account', 'role_id')
    op.drop_index(op.f('ix_Role_id'), table_name='Role')
    op.drop_table('Role')
    # ### end Alembic commands ###
